// Generated by `npm run db:types`. DO NOT EDIT BY HAND.
// This file is a placeholder until first generation against Supabase project vvprodiuwraceabviyes.

export type Database = {
  public: Record<string, never>
  billing: Record<string, never>
}
